apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue-deployment
  labels:
    app: flask-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-blue
  template:
    metadata:
      labels:
        app: flask-blue
    spec:
      containers:
        - name:  flask-blue
          image: ovolmar/flask-blue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
