apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-blue
  template:
    metadata:
      labels:
        app: flask-blue

    spec:
      containers:
        - name: flask-blue-container
          image: ovolmar/${IMAGE_NAME}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

