apiVersion: v1
kind: Service
metadata:
  name: capstone-weather-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: capstone-weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: capstone-weather-service-nodeport
spec:
  type: NodePort
  selector:
    app: capstone-weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: capstone-weather-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstone-weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
