apiVersion: v1
kind: Service
metadata:
  name: sample-flask-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: sample-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: sample-flask-service-nodeport
spec:
  type: NodePort
  selector:
    app:  sample-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: sample-flask-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: sample-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
