apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacapstone-k8s-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1d: { id: subnet-06d77d27686e217df }
      us-east-1c: { id: subnet-0d1c62c4231401855 }


nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 4

  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 4

