apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacapstone-k8s-cluster
  region: us-east-1

ManagedNodeGroups:
  - name: NodeGroup-1
    minSize: 2
    maxSize: 6
    desiredCapacity: 3
    availabilityZones: ["us-east-1d", "us-east-1c"] 
    VolumeSize: 20
    instanceType: t2.micro
    ssh:
      allow: true
      publicKeyPath: ~/nanodegre/udapeople.pem
      publickeyName:  udapeople
      sourcesecurityGroupIds: ["sg-02d6dd2d173beefee"]
    labels: {role: worker}
    tags:
      nodegroup-role: worker
      
  - name: NodeGroup-2
    instanceType: t2.micro
    minSize: 2
    maxSize: 3

