apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-flask-deployment
  labels:
    app: sample-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-flask
  template:
    metadata:
      labels:
        app: sample-flask
    spec:
      containers:
        - name:  sample-flask
          image: ovolmar/flask-sample:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
