apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-weather-deployment
  labels:
    app: capstone-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-weather
  template:
    metadata:
      labels:
        app: capstone-weather
    spec:
      containers:
        - name: capstone-weather
          image: ovolmar/capstone-weather:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080