---

- hosts: localhost
  tasks:
    - name: "Deploying application to EKS"
      shell: |
        /usr/local/bin/aws eks update-kubeconfig --name udacapstone-k8s-cluster --region ${AWS_DEFAULT_REGION} 
        kubectl apply -f infrastructure/bluepod.yml
        kubectl apply -f infrastructure/blue-services.yml
        kubectl apply -f infrastructure/ingress.yml
        kubectl expose deployment flask-capstone --type=ClusterIP --name=service-cluser-ip